# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "uhci_hcd" "ehci_pci" "ahci" "firewire_ohci" "usb_storage" "sd_mod" "sr_mod" "sdhci_pci" ];
  boot.kernelModules = [ "fuse" ];
  boot.extraModulePackages = [ ];

 fileSystems = [
   { mountPoint = "/";
     device = "/dev/disk/by-uuid/6c9536e7-0007-48f7-b008-958f1c2770c5";
     fsType = "ext4";
   }
   { mountPoint = "/home";
     device = "/dev/disk/by-uuid/aa346bff-b0bb-421b-a5b6-08f2c907ec59";
     fsType = "ext4";
   }
   ];

  swapDevices =
    [ { device = "/dev/disk/by-uuid/36865c59-7abf-425a-a2f1-2888619f60a6"; }
    ];

  nix.maxJobs = lib.mkDefault 2;
}
